//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/XRGridControllerActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @XRGridControllerActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @XRGridControllerActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""XRGridControllerActions"",
    ""maps"": [
        {
            ""name"": ""XRGridControls"",
            ""id"": ""362089d8-4876-4785-9414-37b61fd7416d"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""ac739bcf-15a9-43dd-90b3-cd8fe06dc364"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PlaceCube"",
                    ""type"": ""Button"",
                    ""id"": ""6bf8819c-ad17-4a7c-b97f-837ead397f9a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RemoveCube"",
                    ""type"": ""Button"",
                    ""id"": ""4cd5e78e-933b-4c50-9f03-a7d6ad0d9c14"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""26aab20e-c390-49cb-96b2-e4d1c3fb2f7e"",
                    ""path"": ""<XRController>{LeftHand}/{Primary2DAxis}"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77e7565b-6833-47a6-bccf-e308d23e5138"",
                    ""path"": ""<OculusTouchController>{RightHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceCube"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2962f517-f6c3-4e46-abce-4092306f93e0"",
                    ""path"": ""<OculusTouchController>{RightHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RemoveCube"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // XRGridControls
        m_XRGridControls = asset.FindActionMap("XRGridControls", throwIfNotFound: true);
        m_XRGridControls_Move = m_XRGridControls.FindAction("Move", throwIfNotFound: true);
        m_XRGridControls_PlaceCube = m_XRGridControls.FindAction("PlaceCube", throwIfNotFound: true);
        m_XRGridControls_RemoveCube = m_XRGridControls.FindAction("RemoveCube", throwIfNotFound: true);
    }

    ~@XRGridControllerActions()
    {
        UnityEngine.Debug.Assert(!m_XRGridControls.enabled, "This will cause a leak and performance issues, XRGridControllerActions.XRGridControls.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // XRGridControls
    private readonly InputActionMap m_XRGridControls;
    private List<IXRGridControlsActions> m_XRGridControlsActionsCallbackInterfaces = new List<IXRGridControlsActions>();
    private readonly InputAction m_XRGridControls_Move;
    private readonly InputAction m_XRGridControls_PlaceCube;
    private readonly InputAction m_XRGridControls_RemoveCube;
    public struct XRGridControlsActions
    {
        private @XRGridControllerActions m_Wrapper;
        public XRGridControlsActions(@XRGridControllerActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_XRGridControls_Move;
        public InputAction @PlaceCube => m_Wrapper.m_XRGridControls_PlaceCube;
        public InputAction @RemoveCube => m_Wrapper.m_XRGridControls_RemoveCube;
        public InputActionMap Get() { return m_Wrapper.m_XRGridControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(XRGridControlsActions set) { return set.Get(); }
        public void AddCallbacks(IXRGridControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_XRGridControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_XRGridControlsActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @PlaceCube.started += instance.OnPlaceCube;
            @PlaceCube.performed += instance.OnPlaceCube;
            @PlaceCube.canceled += instance.OnPlaceCube;
            @RemoveCube.started += instance.OnRemoveCube;
            @RemoveCube.performed += instance.OnRemoveCube;
            @RemoveCube.canceled += instance.OnRemoveCube;
        }

        private void UnregisterCallbacks(IXRGridControlsActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @PlaceCube.started -= instance.OnPlaceCube;
            @PlaceCube.performed -= instance.OnPlaceCube;
            @PlaceCube.canceled -= instance.OnPlaceCube;
            @RemoveCube.started -= instance.OnRemoveCube;
            @RemoveCube.performed -= instance.OnRemoveCube;
            @RemoveCube.canceled -= instance.OnRemoveCube;
        }

        public void RemoveCallbacks(IXRGridControlsActions instance)
        {
            if (m_Wrapper.m_XRGridControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IXRGridControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_XRGridControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_XRGridControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public XRGridControlsActions @XRGridControls => new XRGridControlsActions(this);
    public interface IXRGridControlsActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnPlaceCube(InputAction.CallbackContext context);
        void OnRemoveCube(InputAction.CallbackContext context);
    }
}
